[project]
name = "contextor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "anthropic>=0.122.0",
    "beautifulsoup4>=4.15.0",
    "chromadb>=1.5.9",
    "pypdf>=6.16.1",
    "pyyaml>=6.0.3",
    "sentence-transformers>=5.7.0",
    "tqdm>=4.70.0",
]

[project.scripts]
contextor = "contextor:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
